### ISSUE TITLE
Welcome page formatting

### ISSUE THREAD

**Issue by anedergaard** [Docopedia/docopedia#1]
![skaermbillede 2015-05-18 19 37 00](https://cloud.githubusercontent.com/assets/4113918/7686360/83af0210-fd95-11e4-9a5c-5594ec8c8313.png)

blå bjælke går ikke hele vejen
Google Chrome Version 42.0.2311.152 m

**Comment by chougaard** [comment]
Hvilken blå bjælke er der tale om? Jeg ser kun en blå firkant som er placeholder for et logo.

**Comment by anedergaard** [comment]
Ah, jeg troede den skulle gå hele vejen over (place holderen), da den gør det på mobile devices

**Comment by chougaard** [comment]
Closing this one, since not a bug, but part of Work in progress
