### ISSUE TITLE
Adding new category to technology unable to deselect already created category 

### ISSUE THREAD

**Issue by anedergaard** [Docopedia/docopedia#11]
Selecting existing category 
![screenshot_2015-05-19-07-48-01](https://cloud.githubusercontent.com/assets/4113918/7696259/ab5004e8-fdfb-11e4-98f2-0e3cb0d3d8c6.png)

Trying to create new category, although not possible 
![screenshot_2015-05-19-07-48-45](https://cloud.githubusercontent.com/assets/4113918/7696260/b07cc492-fdfb-11e4-95b7-27921f011570.png)

**Comment by chr22** [comment]
What's the problem here the "ADD CATEGORY" button seems to be active?

**Comment by chr22** [comment]
Ahh you want to deselect. What happends if you press the clear button?

**Comment by anedergaard** [comment]
Ahh, lack of coffee seemed to be the problem
