### ISSUE TITLE
Unable to login/create new user

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#12]
I may have mistyped my username, i'm not sure. Either that or i'm entering something wrong. When i try to create a new user with the same email i get a notification saying System.String[].

So what i'm typing:

First name: "Lars"
Last name: "von Qualen"
Username: "larsvonqualen"
Email: "larsvonqualen(snabela)gmail(punktum)com"
Password: Six valid characters

It seemed to work the first time, but then i couldnt sign in :smile:

**Comment by chr22** [comment]
You can only create one user per email address, so it must have worked the first time. Can you try again?

**Comment by LarsVonQualen** [comment]
Works like a charm with my new identity as "Don Johnson" :wink: 

Could you check if the username that i signed up with in the first place corresponds with the one in the database?

**Comment by chr22** [comment]
You typed "larsvonquale" not "larsvonqualen" in username ;)

**Comment by LarsVonQualen** [comment]
I KNEW IT! :smile:

**Comment by chr22** [comment]
:+1:
