### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#13]
I created a technology named "<script>alert('herp derp xss');</script>" if i then use the technology search sidebar or the search on the technology page, my javascript gets executed.

Goto Technology
Start searching for: "xss"

**Comment by chr22** [comment]
Cool. We will look into it.

**Comment by LarsVonQualen** [comment]
The name was script tags with an alert inside, seems like Github uses some aggressive filtering :-)

**Comment by chr22** [comment]
I looked it up in the database. It seems we must do some manuel sanitizing.

**Comment by LarsVonQualen** [comment]
I hate to say i told you so :wink:

**Comment by chr22** [comment]
Fixed and ready for next release
