### ISSUE TITLE
IE needs some love

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#14]
The site is really laggy in IE11, and is useless in IE9. But since IE9 sucks, that's okay. But the laggy part is annoying. Would it be possible to disable some of the material design elements, it seems to me that's where the problem is.

**Comment by chr22** [comment]
I think we should wait with this and see if the Angular Material team figures something out.

https://github.com/angular/material/issues/2821

**Comment by chr22** [comment]
https://github.com/angular/material/issues/3101

**Comment by chr22** [comment]
https://github.com/angular/material/issues/1771
