### ISSUE TITLE
Use markdown as editor

### ISSUE THREAD

**Issue by flemse** [Docopedia/docopedia#15]
You should consider changing your editor to markdown.
- It will be easier for you to manage codewise.
- It will remove a closed source dependency.
### Links
- [Is markdown friendly enough for non technical users?](http://ux.stackexchange.com/questions/15919/is-markdown-friendly-enough-for-non-technical-users)
- [possible editor](https://github.com/benweet/stackedit/)
- [Another editor](https://github.com/bergie/hallo)

**Comment by LarsVonQualen** [comment]
# Markdown er awesome... :smile:

+1000000000 :smile:

``` javascript
alert("herp derp");
```

**Comment by chr22** [comment]
We have chosen to keep our wysiwyg editor, but we have taken note of your idea.

We want users to be able to write on our site without having to learn a whole new language first. The only challenging we want our users to have is to come up with great content.
