### ISSUE TITLE
Horizontal scrollbar in sidebar

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#18]
See screenshot:

![Screenshot of Docopedia](https://dl.dropboxusercontent.com/u/13662480/Docopedia%20Screenshot-1.PNG)

**Comment by LarsVonQualen** [comment]
Signing in and clicking Admin Panel gives me scrollbars in the top left corner too..

**Comment by LarsVonQualen** [comment]
Located the bug to this margin property:
![Docopedia screenshot](https://dl.dropboxusercontent.com/u/13662480/Docopedia%20Screenshot-5.png)

**Comment by chougaard** [comment]
This is great. Keem 'em coming ;)

We'll get this in the pipeline for next version (which is not scheduled yet). For some reason this bug doesn't happen in Firefox.
