### ISSUE TITLE
Pressing buttom of items in top menu, doesn't change page/state

### ISSUE THREAD

**Issue by chougaard** [Docopedia/docopedia#22]
If you click on the very buttom of the tabs in the top menu, the highlight changes, but the state doesn't.

This is due to a "hack" we are using, to allow for Ctrl + Click to open link in new tap. This is a problem with the angular material framework we are using for ui elements.

I've created a codepen to illustrate the problem:
http://codepen.io/Belicosus/pen/qdXRzV

There is a free beer on the line, for the one who solves the problem.

Note: To test the open new tab in codepen, insert href="" on the button/tab/whatever you end up with.

**Comment by chr22** [comment]
I got it

**Comment by chougaard** [comment]
You should create a pull request then
