### ISSUE TITLE
Item title locked after creating tech

### ISSUE THREAD

**Issue by flemse** [Docopedia/docopedia#27]
After creating the tech. docker i was redirected to this page. That is nice because i would properly begin writing an item :+1: 
However im unable to edit the title.

![image](https://cloud.githubusercontent.com/assets/4114289/8191316/b3657604-1467-11e5-87cf-533fa8a01c09.png)

**Comment by flemse** [comment]
Ok. I see i missunderstod it.

I guess its the blue title "Create description item for: Docker" that i find a bit misleading.

**Comment by chr22** [comment]
Exactly. We will try to make it more clear what the page is for.
