### ISSUE TITLE
Login dialog isn't center in Safari

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#31]
![Login dialog](https://dl.dropboxusercontent.com/u/13662480/Docopedia%20Login%20Dialog.png)

**Comment by chougaard** [comment]
Vertical centering?

**Comment by LarsVonQualen** [comment]
Yes. The login dialog is also to small compared to Chrome :)

**Comment by chr22** [comment]
This seems to be a caching problem
