### ISSUE TITLE
Document Creation mode Add Tags focus freezes page

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#37]
If i have focus in "Add Tags" i cant scroll the page anymore, and a weird shadow appears in the background.

![](https://dl.dropboxusercontent.com/u/13662480/add%20tags.png)

**Comment by chougaard** [comment]
This is a bug in the Angular Material library. Should be fixed in the next version. There is currently an RC of Material out, but we are not going to upgrade just yet.
