### ISSUE TITLE
As a user i want a cancel button on create and edit pages so that i easily can navigate back

### ISSUE THREAD

**Issue by LarsVonQualen** [Docopedia/docopedia#38]

**Comment by chougaard** [comment]
This is more of a concept thing. Do you want a "Cancel" button, or do you use the tools in the browser like navigate back?

**Comment by LarsVonQualen** [comment]
I use both to be honest. But im thinking of this as a creation process because i started out by creating a tech, and i would prefer to be able to cancel the whole process.

**Comment by chr22** [comment]
I dont think it is necessary with a cancel button, because the browser back button will do the exact same thing. Others agree with me: http://www.nngroup.com/articles/reset-and-cancel-buttons/
