### ISSUE TITLE
Creating a new root langauge

### ISSUE THREAD

**Issue by flemse** [Docopedia/docopedia#4]
How do you create a new root langauge? i get this error when i try.
![skaermbillede 2015-05-18 kl 22 20 21](https://cloud.githubusercontent.com/assets/4114289/7689394/2670e99e-fdac-11e4-8106-2fbc893cda51.png)

**Comment by chougaard** [comment]
Currently, we do not support creation of Root techs/languages. This is not limited by features, but a choice we've made. The thought is, that all root langauges would be added during development, and should serve as the top most items on the website. All content from users should fit under these root techs.

That's the basic idea. If this needs to be revised (in your opinion), please let us know.

Right now, I'll create a note to add Rust as a root tech first thing in the morning ;)

**Comment by flemse** [comment]
Roger that :+1:

**Comment by chougaard** [comment]
The concept of this has been reworked in the new version, and is therefore solved.
