### ISSUE TITLE
Visual bug from navigation

### ISSUE THREAD

**Issue by flemse** [Docopedia/docopedia#5]
I think it is from hitten enter after a search. Note it is on safari :)
![skaermbillede 2015-05-18 kl 22 24 36](https://cloud.githubusercontent.com/assets/4114289/7689457/baca6b9c-fdac-11e4-95eb-a36739fe1410.png)

**Comment by flemse** [comment]
Something along the same lines on chrome:

![skaermbillede 2015-05-18 kl 22 27 00](https://cloud.githubusercontent.com/assets/4114289/7689493/10e4a916-fdad-11e4-8b07-100ea03e81f5.png)

**Comment by chr22** [comment]
The Chrome layout is intentional, but something we must find a better solution to in a future release.

Thougt it is definitely a bug in Safari.

**Comment by chr22** [comment]
Closed your second issue
