### ISSUE TITLE
hover effect misplaced

### ISSUE THREAD

**Issue by flemse** [Docopedia/docopedia#7]
Scrolling seems to mess with the hover effects.

![skaermbillede 2015-05-18 kl 22 37 04](https://cloud.githubusercontent.com/assets/4114289/7689685/7c11bf20-fdae-11e4-8826-0bc4d9b6f6ac.png)

**Comment by chr22** [comment]
This seems to be a known problem with Angular Material (https://github.com/angular/material/issues/2406) that should be fixed in the next release.

I think we will disable it until they fix it.

**Comment by flemse** [comment]
:+1:

**Comment by chr22** [comment]
It is still very much a beta UI framework, so there are unfortunately many of these small bugs :(
