### ISSUE TITLE
Froala Editor floating on mobile device 

### ISSUE THREAD

**Issue by anedergaard** [Docopedia/docopedia#9]
![screenshot_2015-05-19-07-27-43](https://cloud.githubusercontent.com/assets/4113918/7696042/fe10bb94-fdf8-11e4-897b-572301ec96d9.png)
Graphical issue when editing with Froala Editor and then scrolling upwards on the page

**Comment by chr22** [comment]
Yearh I have seen this as well. We will investigate the issue and maybe disable the floating function.
